// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvcdkzmgdnykefogfrmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y2Rrem1nZG55a2Vmb2dmcm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODA3NDEsImV4cCI6MjA3MjY1Njc0MX0.BNcMPQIIxNYlyDGSrtaHJJj2ZdWztQRKV2G8lOg9YmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});